import { useState, Fragment } from 'react';

// ─── Color maps ──────────────────────────────────────────────────────────────

const PLAN_TYPE = {
  COLD:      { bg: 'bg-[#1B4F8A]', label: 'COLD',      desc: 'Cold IP / New Sender' },
  MIGRATION: { bg: 'bg-[#E8652A]', label: 'MIGRATION', desc: 'ESP Migration' },
  REHAB:     { bg: 'bg-red-600',   label: 'REHAB',     desc: 'Reputation Rehabilitation' },
};

const PRIORITY = {
  HIGH:   { badge: 'bg-red-100 text-red-700' },
  MEDIUM: { badge: 'bg-amber-100 text-amber-800' },
  LOW:    { badge: 'bg-gray-100 text-gray-500' },
};

const PHASE_STYLE = {
  Ramp:   { row: 'bg-blue-50',    border: 'border-l-blue-400',    header: 'bg-blue-100 text-blue-800',    dot: 'bg-blue-500',    ring: 'ring-blue-200'    },
  Build:  { row: 'bg-emerald-50', border: 'border-l-emerald-400', header: 'bg-emerald-100 text-emerald-800', dot: 'bg-emerald-500', ring: 'ring-emerald-200' },
  Cruise: { row: 'bg-violet-50',  border: 'border-l-violet-400',  header: 'bg-violet-100 text-violet-800', dot: 'bg-violet-500',  ring: 'ring-violet-200'  },
};

const GATE_STYLE = {
  green:  { row: 'bg-green-50',  border: 'border-l-green-500',  dot: 'bg-green-500',  badge: 'bg-green-100 text-green-700',   label: 'text-green-800',  action: 'text-gray-700' },
  yellow: { row: 'bg-amber-50',  border: 'border-l-amber-500',  dot: 'bg-amber-400',  badge: 'bg-amber-100 text-amber-800',   label: 'text-amber-900',  action: 'text-gray-700' },
  red:    { row: 'bg-red-50',    border: 'border-l-red-500',    dot: 'bg-red-500',    badge: 'bg-red-100 text-red-700',       label: 'text-red-900',    action: 'text-gray-700' },
  black:  { row: 'bg-gray-900',  border: 'border-l-gray-600',   dot: 'bg-gray-400',   badge: 'bg-gray-700 text-gray-200',     label: 'text-gray-100',   action: 'text-gray-300' },
};

// ─── Shared sub-components ───────────────────────────────────────────────────

function ChevronIcon({ open }) {
  return (
    <svg
      className={`w-4 h-4 text-gray-400 transition-transform duration-200 ${open ? 'rotate-90' : ''}`}
      fill="none" viewBox="0 0 24 24" stroke="currentColor"
    >
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
    </svg>
  );
}

function SectionCard({ number, title, open, onToggle, children }) {
  return (
    <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between px-6 py-4 border-b border-gray-100 hover:bg-gray-50 transition-colors text-left"
        aria-expanded={open}
      >
        <div className="flex items-center gap-3">
          <span className="flex items-center justify-center w-6 h-6 rounded-full bg-[#1B4F8A] text-white text-xs font-bold shrink-0">
            {number}
          </span>
          <span className="text-sm font-semibold text-gray-900">{title}</span>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs text-gray-400">{open ? 'Collapse' : 'Expand'}</span>
          <ChevronIcon open={open} />
        </div>
      </button>
      {open && <div>{children}</div>}
    </div>
  );
}

function SectionLabel({ children }) {
  return (
    <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-2">{children}</p>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

export default function PlanRenderer({ plan }) {
  const [open, setOpen] = useState({ header: true, checklist: true, schedule: true, gates: true, isp: true });
  const [checked, setChecked] = useState(() => {
    try { return JSON.parse(localStorage.getItem('inboxable-checklist') || '{}'); }
    catch { return {}; }
  });
  const [activeIspIdx, setActiveIspIdx] = useState(0);

  const toggle = (key) => setOpen((prev) => ({ ...prev, [key]: !prev[key] }));

  const toggleCheck = (id) => {
    setChecked((prev) => {
      const next = { ...prev, [id]: !prev[id] };
      localStorage.setItem('inboxable-checklist', JSON.stringify(next));
      return next;
    });
  };

  const planType   = PLAN_TYPE[plan.type] ?? PLAN_TYPE.COLD;
  const qualIsps   = plan.ispGuidance.filter((isp) => isp.share > 5);
  const checkedCnt = plan.checklist.filter((item) => checked[item.id]).length;
  const progressPct = Math.round((plan.currentDay / plan.duration) * 100);

  const byPhase = plan.phases.map((ph) => ({
    phase: ph,
    rows: plan.warmupSchedule.filter((r) => r.phase === ph.name),
  }));

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Top attribution bar */}
      <div className="bg-[#1B4F8A] text-white/80 text-xs py-2 px-6 text-center tracking-wide">
        Generated by <span className="text-white font-semibold">Inboxable</span> · Powered by{' '}
        <span className="text-white font-semibold">Ongage AI</span>
      </div>

      {/* Page header */}
      <div className="border-b border-gray-200 bg-white px-6 py-5">
        <div className="max-w-7xl mx-auto flex flex-wrap items-center gap-3">
          <span className={`inline-flex items-center px-3 py-1 rounded-md text-xs font-bold tracking-widest text-white ${planType.bg}`}>
            {planType.label}
          </span>
          <div>
            <h1 className="text-lg font-bold text-gray-900 leading-tight">
              Email Warmup Plan — {planType.desc}
            </h1>
            <p className="text-xs text-gray-400 mt-0.5">
              Generated {new Date(plan.generatedAt).toLocaleDateString('en-US', { dateStyle: 'long' })}
              &nbsp;·&nbsp; {plan.duration}-day schedule
            </p>
          </div>
        </div>
      </div>

      {/* Body */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="lg:flex lg:items-start lg:gap-8">

          {/* ── Main content ─────────────────────────────────────────────── */}
          <div className="flex-1 min-w-0 space-y-5">

            {/* 1 · Plan Overview */}
            <SectionCard number="1" title="Plan Overview" open={open.header} onToggle={() => toggle('header')}>
              <div className="px-6 py-5 space-y-5">

                {/* Type / Duration */}
                <div className="flex flex-wrap items-center gap-4">
                  <div>
                    <SectionLabel>Plan Type</SectionLabel>
                    <span className={`inline-flex items-center px-3 py-1 rounded-md text-sm font-bold tracking-wider text-white ${planType.bg}`}>
                      {planType.label}
                    </span>
                  </div>
                  <div>
                    <SectionLabel>Duration</SectionLabel>
                    <span className="text-sm font-semibold text-gray-900">{plan.duration} days</span>
                    <span className="text-sm text-gray-400 ml-2">(Day {plan.currentDay} today)</span>
                  </div>
                  <div>
                    <SectionLabel>Current Phase</SectionLabel>
                    <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded text-xs font-semibold ${PHASE_STYLE[plan.currentPhase]?.header ?? 'bg-gray-100 text-gray-700'}`}>
                      {plan.currentPhase}
                    </span>
                  </div>
                </div>

                {/* ISP Priorities */}
                <div>
                  <SectionLabel>ISP Priority</SectionLabel>
                  <div className="flex flex-wrap gap-2">
                    {plan.ispPriorities.map((isp) => (
                      <span
                        key={isp.name}
                        className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-medium ${PRIORITY[isp.priority]?.badge ?? 'bg-gray-100 text-gray-600'}`}
                      >
                        {isp.name}
                        <span className="opacity-50">{isp.share}%</span>
                        <span className="font-bold opacity-60">{isp.priority}</span>
                      </span>
                    ))}
                  </div>
                </div>

                {/* Risk Flags */}
                {plan.riskFlags.length > 0 && (
                  <div>
                    <SectionLabel>Risk Flags</SectionLabel>
                    <div className="space-y-2">
                      {plan.riskFlags.map((flag, i) => (
                        <div
                          key={i}
                          className={`flex items-start gap-3 rounded-lg border px-4 py-3 text-sm ${
                            flag.level === 'red'
                              ? 'bg-red-50 border-red-200 text-red-800'
                              : 'bg-amber-50 border-amber-200 text-amber-800'
                          }`}
                        >
                          <span className="mt-0.5 text-base leading-none shrink-0">
                            {flag.level === 'red' ? '🔴' : '🟡'}
                          </span>
                          {flag.message}
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </SectionCard>

            {/* 2 · Pre-Warmup Checklist */}
            <SectionCard number="2" title="Pre-Warmup Checklist" open={open.checklist} onToggle={() => toggle('checklist')}>
              <div className="px-6 py-5">
                <div className="flex items-center justify-between mb-3">
                  <p className="text-sm text-gray-500">Complete all items before Day 1.</p>
                  <span className={`text-sm font-semibold ${checkedCnt === plan.checklist.length ? 'text-emerald-600' : 'text-[#1B4F8A]'}`}>
                    {checkedCnt} / {plan.checklist.length}
                  </span>
                </div>
                {/* Progress bar */}
                <div className="h-1.5 bg-gray-100 rounded-full mb-5 overflow-hidden">
                  <div
                    className="h-full bg-[#1B4F8A] rounded-full transition-all duration-500"
                    style={{ width: `${(checkedCnt / plan.checklist.length) * 100}%` }}
                  />
                </div>
                <div className="space-y-3">
                  {plan.checklist.map((item) => {
                    const isDone = !!checked[item.id];
                    return (
                      <label key={item.id} className="flex items-start gap-3 cursor-pointer group">
                        <div className="mt-0.5 shrink-0">
                          <input type="checkbox" checked={isDone} onChange={() => toggleCheck(item.id)} className="sr-only" />
                          <div className={`w-5 h-5 rounded border-2 flex items-center justify-center transition-colors ${
                            isDone ? 'bg-[#1B4F8A] border-[#1B4F8A]' : 'border-gray-300 group-hover:border-[#1B4F8A]'
                          }`}>
                            {isDone && (
                              <svg className="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                              </svg>
                            )}
                          </div>
                        </div>
                        <div>
                          <p className={`text-sm font-medium transition-colors ${isDone ? 'line-through text-gray-400' : 'text-gray-800'}`}>
                            {item.item}
                          </p>
                          <p className="text-xs text-gray-400 mt-0.5">{item.reason}</p>
                        </div>
                      </label>
                    );
                  })}
                </div>
              </div>
            </SectionCard>

            {/* 3 · Warmup Schedule */}
            <SectionCard number="3" title="Warmup Schedule" open={open.schedule} onToggle={() => toggle('schedule')}>
              <div className="overflow-x-auto">
                <table className="w-full text-sm border-collapse">
                  <thead>
                    <tr className="bg-gray-50 border-b border-gray-200">
                      {['Day', 'Volume', 'Segments', 'Throttle', 'Notes'].map((h) => (
                        <th key={h} className="text-left px-4 py-3 text-[10px] font-bold uppercase tracking-widest text-gray-400 whitespace-nowrap">
                          {h}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {byPhase.map(({ phase, rows }) => {
                      const ps = PHASE_STYLE[phase.name] ?? PHASE_STYLE.Ramp;
                      return (
                        <Fragment key={phase.name}>
                          {/* Phase header row */}
                          <tr>
                            <td colSpan={5} className={`px-4 py-2 text-[10px] font-bold uppercase tracking-widest border-b border-t ${ps.header}`}>
                              Phase: {phase.name} &nbsp;·&nbsp; Days {phase.startDay}–{phase.endDay}
                            </td>
                          </tr>
                          {rows.map((row) => {
                            const isToday = row.day === plan.currentDay;
                            return (
                              <tr
                                key={row.day}
                                className={`border-b border-gray-100 border-l-4 ${ps.row} ${ps.border} ${isToday ? 'outline outline-2 outline-offset-[-2px] outline-[#E8652A]' : ''}`}
                              >
                                <td className="px-4 py-3 font-semibold text-gray-900 whitespace-nowrap">
                                  {row.day}
                                  {isToday && (
                                    <span className="ml-2 text-[9px] font-bold text-[#E8652A] bg-orange-50 border border-orange-200 px-1.5 py-0.5 rounded uppercase tracking-wide">
                                      Today
                                    </span>
                                  )}
                                </td>
                                <td className="px-4 py-3 text-gray-700 tabular-nums">{row.volume.toLocaleString()}</td>
                                <td className="px-4 py-3 text-gray-600">{row.segments}</td>
                                <td className="px-4 py-3 text-gray-600 whitespace-nowrap">{row.throttle}</td>
                                <td className="px-4 py-3 text-gray-400 text-xs">{row.notes}</td>
                              </tr>
                            );
                          })}
                        </Fragment>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </SectionCard>

            {/* 4 · Volume Gates */}
            <SectionCard number="4" title="Volume Gates" open={open.gates} onToggle={() => toggle('gates')}>
              <div className="px-6 py-5">
                <p className="text-sm text-gray-500 mb-4">
                  Evaluate after every send. Gate status determines whether you advance, hold, or stop.
                </p>
                <div className="space-y-3">
                  {plan.volumeGates.map((gate, i) => {
                    const gs = GATE_STYLE[gate.status];
                    return (
                      <div key={i} className={`flex gap-4 rounded-lg px-5 py-4 border-l-4 ${gs.row} ${gs.border}`}>
                        {/* Traffic light indicator */}
                        <div className="shrink-0 flex items-start pt-1">
                          <div className={`w-3 h-3 rounded-full ${gs.dot} ring-2 ring-white shadow`} />
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="flex flex-wrap items-center gap-2 mb-1.5">
                            <span className={`text-[10px] font-bold uppercase tracking-widest px-2 py-0.5 rounded ${gs.badge}`}>
                              {gate.status}
                            </span>
                            <span className={`text-sm font-medium ${gs.label}`}>{gate.threshold}</span>
                          </div>
                          <p className={`text-sm ${gs.action}`}>
                            <span className="font-semibold">Action: </span>{gate.action}
                          </p>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            </SectionCard>

            {/* 5 · ISP Guidance */}
            <SectionCard number="5" title="ISP Guidance" open={open.isp} onToggle={() => toggle('isp')}>
              <div className="px-6 py-5">
                <p className="text-sm text-gray-500 mb-4">
                  Showing ISPs with &gt;5% audience share. Tailored tips for each provider.
                </p>

                {/* Tabs */}
                <div className="flex gap-0 border-b border-gray-200 mb-5 overflow-x-auto">
                  {qualIsps.map((isp, i) => (
                    <button
                      key={isp.isp}
                      onClick={() => setActiveIspIdx(i)}
                      className={`px-4 py-2.5 text-sm font-medium whitespace-nowrap border-b-2 -mb-px transition-colors ${
                        activeIspIdx === i
                          ? 'border-[#1B4F8A] text-[#1B4F8A]'
                          : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                      }`}
                    >
                      {isp.isp}
                      <span className="ml-1.5 text-xs opacity-50">{isp.share}%</span>
                    </button>
                  ))}
                </div>

                {/* Tab content */}
                {qualIsps[activeIspIdx] && (
                  <div>
                    <h3 className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-3">Delivery Tips</h3>
                    <ul className="space-y-2.5 mb-6">
                      {qualIsps[activeIspIdx].tips.map((tip, i) => (
                        <li key={i} className="flex items-start gap-2.5 text-sm text-gray-600">
                          <span className="mt-1.5 shrink-0 w-1.5 h-1.5 rounded-full bg-[#E8652A]" />
                          {tip}
                        </li>
                      ))}
                    </ul>

                    {/* Tools */}
                    {qualIsps[activeIspIdx].tools.length > 0 && (
                      <div>
                        <h3 className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-3">Recommended Tools</h3>
                        <div className="flex flex-wrap gap-2">
                          {qualIsps[activeIspIdx].tools.map((tool) => (
                            <span
                              key={tool}
                              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-gray-50 border border-gray-200 text-xs font-medium text-gray-700"
                            >
                              <svg className="w-3.5 h-3.5 text-[#1B4F8A]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                              </svg>
                              {tool}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            </SectionCard>

          </div>

          {/* ── Sticky sidebar ───────────────────────────────────────────── */}
          <aside className="hidden lg:block lg:w-60 shrink-0">
            <div className="sticky top-6 bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">

              {/* Plan type header */}
              <div className={`px-5 py-4 ${planType.bg}`}>
                <p className="text-[10px] font-bold uppercase tracking-widest text-white/60 mb-1">Plan Type</p>
                <p className="text-xl font-bold text-white">{planType.label}</p>
                <p className="text-white/70 text-xs mt-0.5">{planType.desc}</p>
              </div>

              {/* Progress */}
              <div className="px-5 py-4 border-b border-gray-100">
                <div className="flex items-center justify-between mb-2">
                  <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Progress</p>
                  <p className="text-xs font-medium text-gray-600">Day {plan.currentDay} / {plan.duration}</p>
                </div>
                <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-[#E8652A] rounded-full transition-all"
                    style={{ width: `${progressPct}%` }}
                  />
                </div>
                <p className="text-[10px] text-gray-400 mt-1">{progressPct}% complete</p>
              </div>

              {/* Phase tracker */}
              <div className="px-5 py-4 border-b border-gray-100">
                <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-3">Phases</p>
                <div className="space-y-3">
                  {plan.phases.map((ph) => {
                    const isCurrent = ph.name === plan.currentPhase;
                    const isDone    = plan.currentDay > ph.endDay;
                    const ps        = PHASE_STYLE[ph.name] ?? PHASE_STYLE.Ramp;
                    return (
                      <div key={ph.name} className="flex items-center gap-2.5">
                        <div className={`w-2.5 h-2.5 rounded-full shrink-0 ${
                          isCurrent ? `${ps.dot} ring-2 ring-offset-1 ${ps.ring}` :
                          isDone    ? 'bg-gray-300' : 'bg-gray-200'
                        }`} />
                        <div className="flex-1 min-w-0">
                          <p className={`text-xs font-medium truncate ${
                            isCurrent ? 'text-[#1B4F8A]' :
                            isDone    ? 'text-gray-400 line-through' : 'text-gray-500'
                          }`}>
                            {ph.name}
                          </p>
                          <p className="text-[10px] text-gray-400">Days {ph.startDay}–{ph.endDay}</p>
                        </div>
                        {isCurrent && (
                          <span className="text-[9px] font-bold text-[#E8652A] bg-orange-50 border border-orange-200 px-1.5 py-0.5 rounded uppercase tracking-wide shrink-0">
                            Active
                          </span>
                        )}
                        {isDone && (
                          <svg className="w-3.5 h-3.5 text-emerald-500 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                          </svg>
                        )}
                      </div>
                    );
                  })}
                </div>
              </div>

              {/* Checklist summary */}
              <div className="px-5 py-4 border-b border-gray-100">
                <div className="flex items-center justify-between mb-2">
                  <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Checklist</p>
                  <span className={`text-xs font-semibold ${checkedCnt === plan.checklist.length ? 'text-emerald-600' : 'text-[#1B4F8A]'}`}>
                    {checkedCnt}/{plan.checklist.length}
                  </span>
                </div>
                <div className="h-1.5 bg-gray-100 rounded-full overflow-hidden">
                  <div
                    className={`h-full rounded-full transition-all duration-500 ${checkedCnt === plan.checklist.length ? 'bg-emerald-500' : 'bg-[#1B4F8A]'}`}
                    style={{ width: `${(checkedCnt / plan.checklist.length) * 100}%` }}
                  />
                </div>
              </div>

              {/* Sections quick-jump */}
              <div className="px-5 py-4">
                <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-2">Sections</p>
                <div className="space-y-1">
                  {[
                    { key: 'header',    label: 'Plan Overview'    },
                    { key: 'checklist', label: 'Checklist'        },
                    { key: 'schedule',  label: 'Warmup Schedule'  },
                    { key: 'gates',     label: 'Volume Gates'     },
                    { key: 'isp',       label: 'ISP Guidance'     },
                  ].map(({ key, label }) => (
                    <button
                      key={key}
                      onClick={() => setOpen((prev) => ({ ...prev, [key]: true }))}
                      className="flex items-center gap-2 text-xs text-gray-500 hover:text-[#1B4F8A] transition-colors w-full text-left py-0.5"
                    >
                      <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${open[key] ? 'bg-[#1B4F8A]' : 'bg-gray-200'}`} />
                      {label}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          </aside>

        </div>
      </div>
    </div>
  );
}
